version: '3.8'
services:
  mongodb:
    image: "mongo:4.0-xenial"
    ports:
      - "27017:27017"
  backend: 
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
  frontend: 
    build: ./frontend/login-mern-vite
    ports:
     - "5173:5173"
    
volumes:
  data:
  logs: 